# Docker Compose override for development
# This file is automatically loaded by docker-compose and overrides settings in docker-compose.yml

version: '3.8'

services:
  backend:
    # Development overrides
    environment:
      - DEBUG=true
      - RELOAD=true
    volumes:
      # Mount source code for hot reload
      - ./backend:/app
      # Exclude cache directories
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/.mypy_cache
    # Enable hot reload
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    # Development overrides
    volumes:
      # Mount source code for hot reload
      - ./frontend:/app
      # Exclude node_modules to use container's version
      - /app/node_modules
      - /app/dist
    environment:
      - NODE_ENV=development

  # Add pgAdmin for database management in development
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: lionrocket-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@lionrocket.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - lionrocket-network

volumes:
  pgadmin_data: