version: '3.8'

services:
  # Backend API 서버 (SQLite 사용)
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/lionrocket.db
      - JWT_SECRET=super-secret-jwt-key-change-in-production-at-least-32-chars-long
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_HOURS=24
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=development
      - DEBUG=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    volumes:
      - ./backend:/app
      - ./data:/app/data  # SQLite 데이터베이스 파일 저장
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend 웹 서버
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 3000

  # Nginx 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend

# SQLite는 파일 기반이므로 별도의 볼륨 정의가 필요없음
# 데이터는 ./data 디렉토리에 저장됨