version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: lionrocket-backend
    environment:
      - DATABASE_URL=sqlite:///./data/lionrocket.db
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - DEFAULT_ADMIN_USERNAME=${DEFAULT_ADMIN_USERNAME:-admin}
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL:-admin@lionrocket.com}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD:-admin123}
    volumes:
      - ./data:/app/data  # Persist SQLite database
    networks:
      - lionrocket-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: lionrocket-frontend
    networks:
      - lionrocket-network
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: lionrocket-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl  # For SSL certificates
    networks:
      - lionrocket-network
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

networks:
  lionrocket-network:
    driver: bridge

volumes:
  data: