"""Add gender and is_active fields to Character model

Revision ID: 2d2eb4f8e736
Revises: 
Create Date: 2025-08-04 01:28:41.824234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2eb4f8e736'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with nullable=True first
    op.add_column('characters', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=True))
    op.add_column('characters', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Update existing records with default values
    op.execute("UPDATE characters SET gender = 'OTHER' WHERE gender IS NULL")
    op.execute("UPDATE characters SET is_active = 0 WHERE is_active IS NULL")
    
    # Now make the columns non-nullable
    with op.batch_alter_table('characters') as batch_op:
        batch_op.alter_column('gender', nullable=False)
        batch_op.alter_column('is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'is_active')
    op.drop_column('characters', 'gender')
    # ### end Alembic commands ###
