"""Add conversation summary table

Revision ID: 934925fd0dff
Revises: f230593d1df7
Create Date: 2025-08-04 14:11:22.459490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934925fd0dff'
down_revision: Union[str, None] = 'f230593d1df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_character_id'), 'conversation_summaries', ['character_id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_character_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
