"""Replace age with gender in character model

Revision ID: f230593d1df7
Revises: eac6e1ba174e
Create Date: 2025-08-04 03:36:43.928048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f230593d1df7'
down_revision: Union[str, None] = 'eac6e1ba174e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add gender column with temporary default
    op.add_column('characters', sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=True))
    
    # Set default gender for existing records
    op.execute("UPDATE characters SET gender = 'OTHER' WHERE gender IS NULL")
    
    # Make gender column NOT NULL
    with op.batch_alter_table('characters') as batch_op:
        batch_op.alter_column('gender', nullable=False)
    
    # Drop age column
    op.drop_column('characters', 'age')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('age', sa.INTEGER(), nullable=False))
    op.drop_column('characters', 'gender')
    # ### end Alembic commands ###
